// src/components/Youtube.svelte

<script lang="ts">
    export let embedId: string
</script>

<div class="container">
    <iframe
        src={`https://www.youtube.com/embed/${embedId}`}
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
        title="Embedded youtube"
    />
</div>

<style>
    .container {
        position: relative;
        aspect-ratio: 16/9;
    }

    iframe {
        height: 100%;
        width: 100%;
    }
</style>

// src/lib/Youtube.tsx
import { CSSProperties } from "react"

interface YoutubeParams{
    style?: CSSProperties,
    embedId: string
}

export const Youtube = ({embedId, style}: YoutubeParams) => 
    <div style={{
        position: "relative",
        aspectRatio: '16/9',
        ...style
    }}>
        <iframe
            style={{
                // left: 0,
                // top: 0,
                height: "100%",
                width: "100%",
                // position: "absolute"
            }}
            // width="853"
            // height="480"
            src={`https://www.youtube.com/embed/${embedId}`}
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            title="Embedded youtube"
        />
    </div>
