// src/components/creative.tsx
import { portfolioItems, PortfolioTag, RenderPortfolio } from "src/lib/Portfolio";

export const Creative = () => 
<>
    <p>
        When I'm bored, it fills my cup to create beautiful and fun things. Here is a selection of this output.
    </p>
    {RenderPortfolio(portfolioItems.filter(item => item.tag == PortfolioTag.Creative))}
</>

// src/spa_routes/creative.svelte
<script>
    import { portfolioItems, PortfolioTag, RenderPortfolio } from "@src/util/Portfolio";
    import PortfolioList from "@src/components/portfolio_list.svelte";

    const creativePortfolio = portfolioItems.filter(item => item.tag == PortfolioTag.Creative)
</script>

<p>
    When I'm bored, it fills my cup to create beautiful and fun things. Here is a selection of this output.
</p>
<PortfolioList items={creativePortfolio}/>
