// src/components/links.svelte
<script>
    import { mdiAt, mdiCodeTags, mdiGithub, mdiInstagram } from "@mdi/js"

    const linkItems = [
        {
            title: "edeetee@gmail.com",
            url: "mailto:edeetee@gmail.com",
            mdiPath: mdiAt
        },
        {
            title: "Optiphonic",
            url: "https://instagram.com/optiphonic",
            mdiPath: mdiInstagram
        },
        {
            title: "Github",
            url: "https://github.com/edeetee",
            mdiPath: mdiGithub
        },
        {
            title: "Source code",
            url: "https://github.com/edeetee/edeetee.github.io",
            mdiPath: mdiCodeTags
        }
    ]
</script>

{#each linkItems as link}
    <a href={link.url}>
        <svg viewBox="0 0 24 24"><path d={link.mdiPath}></path></svg>
        <h4>{link.title}</h4>
    </a>
{/each}

<style>
    a {
        display: flex;
        flex-direction: row;
        align-items: center;
        margin: 6px 0;
    }

    svg {
        width: 18px;
        height: 18px;
        margin: auto 0;
    }

    h4{
        margin: auto 0;
        padding-left: 4px;
    }
</style>

// src/components/css/links/index.tsx
import { mdiAt, mdiCodeTags, mdiGithub, mdiInstagram } from "@mdi/js"
import Image from "next/image"

interface LinkItem {
    title: string,
    url: string
    mdiPath: string
}

const linkItems: LinkItem[] = [
    {
        title: "Email",
        url: "mailto:edeetee@gmail.com",
        mdiPath: mdiAt
    },
    {
        title: "Optiphonic",
        url: "https://instagram.com/optiphonic",
        mdiPath: mdiInstagram
    },
    {
        title: "Github",
        url: "https://github.com/edeetee",
        mdiPath: mdiGithub
    },
    {
        title: "Source code",
        url: "https://github.com/edeetee/edeetee.github.io",
        mdiPath: mdiCodeTags
    }
]

export const Links: React.FC = () => 
<div>
    {
        linkItems.map((item, i) => 
            <a key={i} href={item.url} style={{display: "flex", flexDirection: "row", alignItems: "center", margin:"6px 0"}}>
                <svg style={{width: "18px", height: "18px", margin: "auto 0"}} viewBox="0 0 24 24"><path d={item.mdiPath}></path></svg>
                <h4 style={{margin: "auto 0", paddingLeft:"4px"}}>{item.title}</h4>
            </a>
        )
    }
</div>
