// src/components/background/index.tsx

//TODO: maybe make component class?

import React, { useEffect } from "react";
import REGL from "regl";
import { FeedbackRenderer } from "src/lib/feedbackRenderer";

const RES_MULTIPLIER = 0.5

export const CanvasRenderer = () => {
    const canvasRef = React.createRef<HTMLCanvasElement>()

    let onMouseMove: ((x: number, y: number) => void)|undefined

    useEffect(() => {
        if(!process.browser)
            return

        const canvas = canvasRef.current

        const glContext = canvas?.getContext("webgl")

        function updateSize(){
            if(canvas && glContext){
                canvas.width = window.innerWidth*RES_MULTIPLIER
                canvas.height = window.innerHeight*RES_MULTIPLIER
                glContext.viewport(0,0, canvas.width, canvas.height)
            }
        }

        window.addEventListener("resize", updateSize)

        updateSize()

        const regl = REGL({
            pixelRatio: 1,
            // canvas: canvas,
            gl: glContext || undefined,
            extensions: [
                'OES_texture_float', 
                // 'GL_OES_texture_float', 
                'WEBGL_color_buffer_float',
                'OES_texture_float_linear'
                // 'WEBGL_texture_float'
            ],
            optionalExtensions: [
                'EXT_color_buffer_float'
            ],
            // optionalExtensions: ['OES_texture_float_linear', "WEBGL_color_buffer_float"],
            onDone(err, regl){
                if(err != null)
                    console.log(err)
            }
        })

        const feedbackRenderer = FeedbackRenderer(regl)

        onMouseMove = feedbackRenderer.onMouseMove

        regl.frame(ctx => {
            feedbackRenderer.onFrame(ctx)
        })
    })
    
    return <canvas ref={canvasRef}
        onMouseMove={e => {if(onMouseMove) onMouseMove(e.clientX, e.clientY)}} 
        style={{
            position: "fixed",
            width: "100vw",
            height: "100vh",
            left: 0,
            top: 0
        }}
    ></canvas>
}

// src/components/background/index.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import {FeedbackRenderer} from './renderer'
    import {constrain} from '@src/util/constrain'
    
    let canvas: HTMLCanvasElement
    const RES_MULTIPLIER = 0.5

    onMount(() => {
        let glContext = canvas.getContext('webgl')

        if(glContext == null)
            throw Error("No valid webgl context")

        let renderer = FeedbackRenderer(glContext)

        function updateSize(){
            if(canvas && glContext){
                canvas.width = window.innerWidth*RES_MULTIPLIER
                canvas.height = window.innerHeight*RES_MULTIPLIER
                glContext.viewport(0,0, canvas.width, canvas.height)
            }
        }

        window.addEventListener("resize", updateSize)
        updateSize()

        function updateMouse(pageX: number, pageY: number){
            const x = constrain((pageX-window.scrollX)/window.innerWidth, 0, 1)
            const y = constrain(1-(pageY-window.scrollY)/window.innerHeight, 0, 1)

            renderer.onMove(x, y)
        }
    
        document.body.addEventListener("touchmove", ev => updateMouse(ev.touches[0].pageX, ev.touches[0].pageY))
        document.body.addEventListener("mousemove", ev => updateMouse(ev.pageX, ev.pageY))
    })
</script>

<canvas id="background" bind:this={canvas} />

<style>
    #background {
        position: fixed;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        z-index: -1;
    }
</style>
